export const ADD_INGREDIENT = "ADD_NEW_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const PURCHASE = "UPDATE_PURCHASABLE";

export const RESET_STORE = "RESET_REDUX_STORE_AFTER_STORING_DATA_IN_FIREBASE";

// .get from firebase
export const ORDERS_LOADED = "ORDERS_LOADED_FROM_FIREBASE";
export const ORDERS_LOADING = "ORDERS_LOADING_FROM_FIREBASE";
export const ORDERS_LOAD_FAILED = "FAILED_TO_LOAD_DATA_FROM_FIREBASE";

// authentication
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS_FROM_FIREBASE";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED_FROM_FIREBASE";
export const AUTHENTICATION_LOADING = "AUTHENTICATION_LOADING_FROM_FIREBASE";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT_FROM_FIREBASE";
export const API_KEY = "AIzaSyCIi4HhOJPopXWU6yV63ASIeDuOFzdky8Y";